[package]
name = "dessa"
version = "0.1.0"
authors = ["Matthew Elphick <matt.a.elphy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
ws = "*"
serde_json = "1.0"